show-current-clan-on-join: true
settings:
  world-name: "world" # The world name where chunk claiming will be enabled
  max-clan-name-length: 16
  min-clan-name-length: 4
  max-prefix-length: 4
  chunk-cost-formula: "100x" # x is the amount of currently claimed chunks by the clan (REQUIRES VAULT)
  enemy-proximity-radius: 3 # the minimum amount of chunks between two different clan chunk claims
  region-proximity-radius: 3 # the minimum amount of chunks between a claimed chunk and a VClans protected WorldGuard region
  invite-expiration: 60*60*24*7 # 7 days
  default-clan-owner-title: "Leader"
  default-clan-member-title: "Member"
  extrude-max-y: 200 # the highest       ...        points on an area marker in BlueMap
  extrude-min-y: 50 #     ... and respectively the lowest ...
  war:
    grace-period: 100 # 24 hours, how long the clan has to prepare for war after a war declaration
    war-duration: 300 # 7 hours, how long the war lasts after the grace period
    war-cooldown: 10 # 24 hours, how long the clan has to wait after a war ends before being able to be involved in another war
clan-tiers:
  # Potion effects for the buffs and debuffs https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
  0:
    label: "[I]"
    player-limit: 5
    chunk-limit: 10
    buffs: [ ]
    debuffs: [ ]
    price: 0 # Doesn't matter if the first tier
  1:
    label: "[II]"
    player-limit: 10
    chunk-limit: 20
    buffs:
      - [ "REGENERATION", 1 ] # applied to clan mates
    debuffs:
      - [ "GLOWING", 1 ]
    price: 20000
  2:
    label: "[III]"
    player-limit: 15
    chunk-limit: 30
    buffs:
      - [ "REGENERATION", 2 ]
      - [ "SPEED", 1 ]
    debuffs:
      - [ "GLOWING", 1 ]
      - [ "DARKNESS", 1 ]
    price: 100000
commands:
  # cooldown can not be applied to some commands that are not required to be sent by a player, for example help or list
  # target-cooldown is the cooldown that is applied to the command that is specified in the target-cooldown field
  # confirmation is the time in seconds the player has to confirm the action
  # confirmation-message is an optional message that is sent to the player when the confirmation is required, if not set the default confirmation message is sent
  #       {confirm-time} - the time left to confirm the action
  default:
    messages: # general messages used by many commands
      no-permission: "You do not have permission to use this command."
      player-only: "This command can only be used by players."
      not-enough-arguments: "Not enough arguments."
      too-many-arguments: "Too many arguments."
      wrong-number-of-arguments: "Wrong number of arguments."
      on-cooldown: "The command is on cooldown. Time left: {time}."
      command-disabled: "This command is disabled. Contact an administrator for more information."
      not-in-clan: "You are not in a clan."
      not-owner: "You are not the owner of your clan."
      never-joined: "That player has never played on this server."
      confirmation-message: "'/confirm' in the next {confirm-time} seconds to confirm the action."
      confirmation-expired: "The confirmation has expired."
      nothing-to-confirm: "There is nothing to confirm."
  clan:
    help:
      enabled: true
      description: "Displays the help menu."
      usage: "/clan help"
      show-command-list: true
      messages:
        header: "=============Clan Commands============="
        content: "
        Thank you for using Valentinos Clans plugin made by Alex_Joo!
        To view the list of available commands, use /clan help.
        "
        list-item: " &7- {item}: &r&l{desc}"
        footer: "======================================="
    list:
      enabled: true
      description: "Lists all clans."
      usage: "/clan list"
      messages:
        clan-list-header: "=============Clans============="
        clan-list-item: "&8 -&r &8{clan-id}&r [{clan-prefix}&r] {clan-name}&r"
        clan-list-footer: "==============================="
        member-list-header: "============Members of {clan-name}============"
        member-list-item: "&8 - [{priority}]&r {rank}&r <{player-name}&r>"
        member-list-footer: "========================================="
        clan-not-found: "The clan {clan-id} does not exist."
    create:
      enabled: true
      target-cooldown: "clan-disband" # This tells that the cooldown bellow will be applied to the disband command. I.E. You can't disband a clan for 30 seconds after creating it.
      cooldown: 60*60*24 # This cooldown is applied to the target-cooldown, which when unspecified will be applied to itself.
      confirmation: 30
      description: "Creates a new clan."
      usage: "/clan create <id>"
      messages:
        success: "You have successfully created the clan - {clan-id}." # {name} will be replaced with the name of the clan. Works on most messages.
        confirmation-message: "Are you sure you want to create this clan with the id [{clan-id}]? This can't be changed! Type /confirm if you are sure"
        already-exists: "Clan with name {clan-id} already exists."
        too-long: "The clan name is too long. Maximum length is 10 characters."
        too-short: "The clan name is too short. Minimum length is 4 characters."
        invalid-characters: "The clan name contains invalid characters. Only lowercase letters and underscores are allowed."
        already-in-clan: "You, {player-name}, are already in a clan. Leave your current clan to create a new one."
    disband:
      enabled: true
      target-cooldown: "clan-create"
      cooldown: 10
      confirmation: 30 # This is the time in seconds the player has to confirm the action.
      description: "Disbands your clan."
      usage: "/clan disband"
      messages:
        success: "You have disbanded the clan {clan-name}."
        no-permission: "You don't have the permission to disband the clan."
        disband-notification: "The clan you are in, {clan-name}, has been disbanded by {player-name}."
        confirmation-message: "Are you sure you want to disband your clan? Type '/confirm' in the next {confirm-time} seconds to confirm the action."
    invite:
      enabled: true
      description: "Invites a player to your clan."
      usage: "/clan invite <player>"
      messages:
        success: "You have invited {target-name} to your clan."
        no-permission: "You don't have the permission to invite players to the clan."
        invitation: "You have been invited to join the clan {clan-name} by {player-name}. Use '/clan join {clan-id}' to accept the invitation."
        invite-self: "You can't invite yourself to your clan."
        already-in-a-clan: "The player {target-name} is already in a clan."
        already-in-the-clan: "That player is already in the clan."
        already-invited: "That player has already been invited to your clan."
        clan-full: "The clan {clan-name} is full."
    kick:
      enabled: true
      description: "Kicks a player from your clan."
      usage: "/clan kick <player>"
      confirmation: 30
      messages:
        success: "You have kicked {target-name} from your clan."
        no-permission: "You don't have the permission to kick players from the clan."
        kicked: "You have been kicked from the clan {clan-name} by {player-name}."
        kicked-notification: "Player {target-name} has been kicked from the clan by {player-name}." # This is sent to all clan members online
        cant-kick-yourself: "You can't kick yourself from your clan."
        target-not-in-clan: "That player is not in your clan."
        insufficient-rank: "Your rank priority is too low to kick {target-name} from the clan."
        confirmation-message: "Are you sure you want to kick {target-name} from your clan? Type '/confirm' in the next {confirm-time} seconds to confirm the action."
    join:
      enabled: true
      description: "Joins a clan if you have been invited."
      usage: "/clan join <clan>"
      messages:
        success: "You have joined the clan {clan-name} successfully!"
        joined-notification: "{player-name} has joined the clan!" # This will be sent to all online clan members when a player joins.
        clan-not-exist: "The clan {clan-id} does not exist."
        not-invited: "You have not been invited to join the clan {clan-name}."
        invite-expired: "The invitation to join the clan {clan-name} has expired."
        already-in-a-clan: "You are already in a clan."
        already-in-the-clan: "You are already in the clan."
        clan-full: "The clan {clan-name} is full."
    leave:
      enabled: true
      description: "Leaves your current clan."
      usage: "/clan leave"
      messages:
        success: "You have left the clan {clan-name} successfully."
        leave-notification: "Your fellow clan member {player-name} has left the clan."
        owner-cant-leave: "You can't leave your clan. Disband it instead."
    rank:
      enabled: true
      description: "Changes the rank of a player in your clan."
      usage: "/clan rank"
      messages:
        success: "You have changed the rank of {target-name} to {rank}."
        rank-changed: "Your rank has been changed to {rank} by {player-name}."
        target-not-in-clan: "{target-name} is not in your clan."
        rank-not-found: "The rank {rank} does not exist."
        rank-priority-low: "Your rank priority is too low"
    color:
      enabled: true
      description: "Changes the color of the clan."
      usage: "/clan color <0-255> <0-255> <0-255>"
      messages:
        success: "You have successfully changed the clan color!"
        invalid-input: "Invalid RGB Input, only accepts: /clan color <0-255> <0-255> <0-255>"
    upgrade:
      enabled: true
      description: "Upgrades the clans tier to gain perks."
      usage: "/clan upgrade"
      confirmation: 30
      messages:
        success: "You have successfully upgraded the clan to tier: {tier-label}"
        confirmation-message: "Are you sure you want to upgrade the clan to tier {tier-label} for the price of ${tier-price}? You have {confirm-time} seconds to /confirm !"
        max-tier: "You already have the highest tier clan!"
        cant-afford: "You can't afford the tier upgrade ({tier-price})"
    chat:
      enabled: true
      description: "Toggles current chat to be only visible for clan members or global."
      usage: "/clan chat"
      messages:
        success: "You have entered {chat} chat."
        no-vault: "Vault has not been properly enabled, contact an administrator for help."
    prefix:
      enabled: true
      description: "Sets the clan's prefix that will be used in chat. Max size is 4, allows for legacy color formatting."
      usage: "/clan prefix <prefix>"
      messages:
        success: "Successfully set the clans prefix to {prefix}"
        too-big: "The max prefix length is {max-length}"
        forbidden-formatting: "Doesn't allow text formatting and the black color"
        invalid-characters: "Invalid characters found. If you want to change color, use &[1-9,a-u]"
    rename:
      enabled: true
      description: "Renames the clan."
      usage: "/clan prefix <name>"
      messages:
        success: "Successfully set the clans name to {name}"
        too-big: "The max clan name length is {max-length}"
        too-small: "The min clan name length is {min-length}"
        forbidden-formatting: "Doesn't allow text formatting and the black color"
        invalid-characters: "Invalid characters found. If you want to change color, use &[1-9,a-u]"
  chunk:
    claim:
      enabled: true
      description: "Claims a chunk for your clan."
      usage: "/chunk claim"
      confirmation: 30
      messages:
        success: "You have claimed the chunk for your clan."
        confirmation-message: "Are you sure you want to claim this chunk for the cost of ${price}? Type '/confirm' in the next {confirm-time} seconds to confirm the action."
        already-claimed: "This chunk is already claimed by the clan - {clan-name}."
        no-permission: "You don't have the permission to claim chunks."
        max-chunks: "You have reached the maximum number ({max-chunks}) of chunks your clan can claim."
        not-adjacent: "You can only claim chunks that are adjacent to your clan's claimed chunks."
        too-close: "You can't claim this chunk because it is too close to another clan's claimed chunk."
        too-close-region: "You can't claim this chunk because it is too close to a VClans protected WorldGuard region."
        wrong-world: "You can't claim chunks in this world."
        cant-afford: "You can't afford this chunk: ${price}."
    unclaim:
      enabled: true
      description: "Unclaims a chunk for your clan."
      usage: "/chunk unclaim"
      messages:
        success: "You have unclaimed the chunk for your clan."
        not-claimed: "This chunk is not claimed by your clan. Currently claimed by {clan-name}."
        no-permission: "You don't have the permission to unclaim chunks."
        territory-split: "You can't unclaim this chunk because it would split your clan's territory."
    radar:
      enabled: true
      description: "Displays the radar of your claimed chunks around you in a 5x5 grid."
      usage: "/chunk radar"
  war:
    declare:
      enabled: true
      description: "Declares a war with another clan."
      usage: "/war declare <clanId>"
      messages:
        success: "You have declared war on the {target-clan}."
        initiator-clan-notification: "{player-name} of this clan has declared war on the clan {target-clan}."
        target-clan-notification: "The clan {initiator-clan} has declared war on your clan!"
        clan-in-war: "The clan {clan-name} is already in war."
        declare-self: "You can't declare war on your own clan."

